language: minimal

dist: bionic
sudo: required
cache: false

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
      - sourceline: 'deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
      - key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-8
      - llvm-8
      - llvm-8-dev
      - lld-8
      - python3
      - python3-setuptools
      - python3-wheel
      - python3-pip
      - ninja-build
      - make
      - wget
      - tar
      - doxygen
      
install:
  - sudo pip3 install meson

  # Install linkle
  - LINKLE_VERSION=v0.2.7
  - wget https://github.com/MegatonHammer/linkle/releases/download/$LINKLE_VERSION/linkle-$LINKLE_VERSION-x86_64-unknown-linux-musl.tar.gz
  - tar -xvf linkle-$LINKLE_VERSION-x86_64-unknown-linux-musl.tar.gz

  # Because Travis ship with an old version of llvm, we remove it to avoid conflicts...
  - sudo rm -rf /usr/local/clang-7.0.0/

script:
  - PATH="$TRAVIS_BUILD_DIR:$PATH" HYDROSPHERE_SYSROOT="${TRAVIS_BUILD_DIR}/sysroot" HYDROSPHERE_LLVM_SUFFIX="-8" make prepare-launch

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/sysroot/usr/share/doc/libhydrosphere/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
